-- =============================================
-- AutoMarket Slovenia - ADD MISSING COLUMNS
-- Run this in Supabase SQL Editor
-- =============================================

-- Basic Info
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_category VARCHAR(50) DEFAULT 'avto';
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_sub_category VARCHAR(100);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_sub_category_detail VARCHAR(100);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS body_type VARCHAR(50);

-- Vehicle Condition
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_condition VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_condition_sub TEXT[];

-- Images & Features
ALTER TABLE cars ADD COLUMN IF NOT EXISTS images TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS feature_ids TEXT[];

-- Fuel Consumption
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_consumption DECIMAL(5,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS emission_class VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS co2_emissions INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS auto_publish_fuel_data BOOLEAN DEFAULT FALSE;

-- Vehicle Age & Ownership
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_age VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_warranty BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_guarantee BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_oldtimer_cert BOOLEAN DEFAULT FALSE;

-- Registration
ALTER TABLE cars ADD COLUMN IF NOT EXISTS first_reg_month VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS first_reg_year INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS technical_valid_until DATE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS owner_count INTEGER;

-- Motor specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_capacity DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_power_kw DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS cylinder_count INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_stroke VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS diff_lock VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS start_type VARCHAR(50);

-- Kamion specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS airbag_count_kamion INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS nosilnost INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS tovorni_prostor DECIMAL(8,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS zadnja_vrata TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS stranska_vrata TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS barva_oblazinjenja VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS oblazinjenje VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS streha_vozila TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vin VARCHAR(50);

-- Tovorna prikolica specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS dolzina DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS sirina DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS stev_osi INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS dovoljena_skupna_tezza INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS volumen DECIMAL(8,2);

-- UTV specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_engine_capacity DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_engine_power_km DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_cylinder_count INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_engine_stroke VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_diff_lock VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_start_type VARCHAR(50);

-- Seller Info
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_name VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_phone VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_user_type VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_verified BOOLEAN DEFAULT FALSE;

-- Stats
ALTER TABLE cars ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';

-- Boost/Promo
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_boost BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS boost_package VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS boost_days INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS boost_spent DECIMAL(8,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS is_promoted BOOLEAN DEFAULT FALSE;

-- Luxury Car
ALTER TABLE cars ADD COLUMN IF NOT EXISTS is_luxury_car BOOLEAN DEFAULT FALSE;

-- Financing
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_financing BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS monthly_budget DECIMAL(10,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS down_payment_type VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS down_payment_value DECIMAL(10,2);

-- Timestamps
ALTER TABLE cars ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE cars ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Done
SELECT 'All columns added to cars table!' AS status;
