-- =============================================
-- AutoMarket Slovenia - ADD ALL MISSING COLUMNS
-- Run this in Supabase SQL Editor
-- =============================================

-- Equipment & Features
ALTER TABLE cars ADD COLUMN IF NOT EXISTS feature_ids TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_condition VARCHAR(100);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_condition_sub TEXT[];

-- Additional Specs
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine VARCHAR(100);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS horsepower INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_capacity DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_power_kw DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS cylinder_count INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS engine_stroke VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS diff_lock VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS start_type VARCHAR(50);

-- Fuel
ALTER TABLE cars ADD COLUMN IF NOT EXISTS fuel_consumption DECIMAL(5,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS emission_class VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS co2_emissions INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS auto_publish_fuel_data BOOLEAN DEFAULT FALSE;

-- Vehicle Age & Ownership
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vehicle_age VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_warranty BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_guarantee BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_oldtimer_cert BOOLEAN DEFAULT FALSE;

-- Registration
ALTER TABLE cars ADD COLUMN IF NOT EXISTS first_reg_month VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS first_reg_year INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS technical_valid_until DATE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS owner_count INTEGER;

-- Kamion specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS airbag_count_kamion INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS nosilnost INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS tovorni_prostor DECIMAL(8,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS zadnja_vrata TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS stranska_vrata TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS barva_oblazinjenja VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS oblazinjenje VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS streha_vozila TEXT[];
ALTER TABLE cars ADD COLUMN IF NOT EXISTS vin VARCHAR(50);

-- Tovorna prikolica specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS dolzina DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS sirina DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS stev_osi INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS dovoljena_skupna_tezza INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS volumen DECIMAL(8,2);

-- UTV specific
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_engine_capacity DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_engine_power_km DECIMAL(6,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_cylinder_count INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_engine_stroke VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_diff_lock VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS utv_start_type VARCHAR(50);

-- Seller Info
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_name VARCHAR(255);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_phone VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_user_type VARCHAR(20);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS seller_verified BOOLEAN DEFAULT FALSE;

-- Boost/Promo
ALTER TABLE cars ADD COLUMN IF NOT EXISTS has_boost BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS boost_package VARCHAR(50);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS boost_days INTEGER;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS boost_spent DECIMAL(8,2);
ALTER TABLE cars ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE cars ADD COLUMN IF NOT EXISTS is_promoted BOOLEAN DEFAULT FALSE;

-- Done
SELECT 'All columns added successfully!' AS status;
