-- ============================================
-- AutoMarket Slovenia - Fix Car Features
-- Drop old table and create new one with correct columns
-- ============================================

-- Drop the old car_features table if it exists
DROP TABLE IF EXISTS car_features CASCADE;

-- Create new car_features table with correct structure
CREATE TABLE car_features (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    subcategory TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_car_features_category ON car_features(category);
CREATE INDEX IF NOT EXISTS idx_car_features_subcategory ON car_features(subcategory);

-- ============================================
-- INSERT ALL CAR FEATURES
-- ============================================
INSERT INTO car_features (name, category, subcategory) VALUES
-- NOTRANJOST - Udobje
('Virtualni Cockpit', 'notranjost', 'udobje'),
('Ambientna osvetlitev notranjosti', 'notranjost', 'udobje'),
('Leseni dodatki notranjosti', 'notranjost', 'udobje'),
('ALU dodatki notranjosti', 'notranjost', 'udobje'),
('Karbonski dodatki notranjosti', 'notranjost', 'udobje'),
('Krom dodatki notranjosti', 'notranjost', 'udobje'),
('Paket za kadilce', 'notranjost', 'udobje'),
('Sportni sedezi', 'notranjost', 'udobje'),
('Komfortni sedezi', 'notranjost', 'udobje'),
('Ortopedski sedezi', 'notranjost', 'udobje'),
('12V vticnica', 'notranjost', 'udobje'),
('Klimatska naprava - rocna', 'notranjost', 'udobje'),
('Sedeži: nastavitev po visini', 'notranjost', 'udobje'),
('Sedeži: el. nastavitev', 'notranjost', 'udobje'),
('Sedeži: paket Memory', 'notranjost', 'udobje'),
('Sedeži: gretje spreda', 'notranjost', 'udobje'),
('Sedeži: gretje zadaj', 'notranjost', 'udobje'),
('Sedeži: hlajenje / ventilacija', 'notranjost', 'udobje'),
('Sedeži: masazna funkcija', 'notranjost', 'udobje'),
('Sredinski naslon za roko med sedezi', 'notranjost', 'udobje'),
('Hladilni predal', 'notranjost', 'udobje'),
('Avtomatska klimatska naprava / digitalna', 'notranjost', 'udobje'),
('Klimatska naprava - 2 conska', 'notranjost', 'udobje'),
('Klimatska naprava - 3 conska', 'notranjost', 'udobje'),
('Klimatska naprava - 4 conska', 'notranjost', 'udobje'),
('Gretje mirujocega vozila (Webasto)', 'notranjost', 'udobje'),
('Tonirana stekla', 'notranjost', 'udobje'),
('Elektricni pomik prednjih stekel', 'notranjost', 'udobje'),
('Elektricni pomik prednjih in zadnjih stekel', 'notranjost', 'udobje'),
('El. nastavijiva zunanja ogledala', 'notranjost', 'udobje'),
('Ogrevanje zunanjih ogledal', 'notranjost', 'udobje'),
('El. zlozijiva zunanja ogledala', 'notranjost', 'udobje'),
('Centralno zaklepanje', 'notranjost', 'udobje'),
('Centralno zaklepanje z daljinskim', 'notranjost', 'udobje'),
('Soft-Close sistem zapiranja', 'notranjost', 'udobje'),
('Sencni rolo za zadnje steklo', 'notranjost', 'udobje'),
('Keyless Go', 'notranjost', 'udobje'),
('Start-Stop sistem', 'notranjost', 'udobje'),
('Elektricni paket', 'notranjost', 'udobje'),
('Nastavijiv volan po visini', 'notranjost', 'udobje'),
('Nastavijiv volan po globini', 'notranjost', 'udobje'),
('Servo volan', 'notranjost', 'udobje'),
('Volanski obroc oblecen v usnje', 'notranjost', 'udobje'),
('Multifunkcijski volan', 'notranjost', 'udobje'),
('Sportni volan', 'notranjost', 'udobje'),
('Ogrevan volanski obroc', 'notranjost', 'udobje'),
('Obvolanski prestavni rocici', 'notranjost', 'udobje'),
('Tempomat', 'notranjost', 'udobje'),
('Aktivni tempomat (Adaptive Cruise Control)', 'notranjost', 'udobje'),
('El. parkima zavora', 'notranjost', 'udobje'),
('El. zapiranje prtljaznika', 'notranjost', 'udobje'),
('Ogrevano vetrobransko steklo', 'notranjost', 'udobje'),

-- INFO_MULTIMEDIA
('Avtoradio', 'info_multimedia', 'avtoradio'),
('Avtoradio / CD', 'info_multimedia', 'avtoradio'),
('Hi-Fi ozvocenje', 'info_multimedia', 'avtoradio'),
('CD izmenjevalnik / strežnik', 'info_multimedia', 'avtoradio'),
('MP3 predvajalnik', 'info_multimedia', 'avtoradio'),
('DVD predvajalnik', 'info_multimedia', 'avtoradio'),
('Trdi disk za shranjevanje podatkov', 'info_multimedia', 'avtoradio'),
('USB prikljucek (iPod, HD...)', 'info_multimedia', 'avtoradio'),
('TV sprejemnik / tuner', 'info_multimedia', 'avtoradio'),
('Bluetooth vmesnik', 'info_multimedia', 'avtoradio'),
('Apple CarPlay', 'info_multimedia', 'avtoradio'),
('Android Auto', 'info_multimedia', 'avtoradio'),
('Digitalni radio DAB', 'info_multimedia', 'avtoradio'),
('Navigacija', 'info_multimedia', 'avtoradio'),
('Navigacija + TV', 'info_multimedia', 'avtoradio'),
('Touch screen', 'info_multimedia', 'avtoradio'),

-- UPORABNOST
('Deljiva zad.klop 1/2 - 1/2', 'uporabnost', 'uporabnost_main'),
('Deljiva zad.klop 1/3 - 2/3', 'uporabnost', 'uporabnost_main'),
('Deljiva zad.klop 1/3-1/3-1/3', 'uporabnost', 'uporabnost_main'),
('Isofix sistem za pritrditev sedeza', 'uporabnost', 'uporabnost_main'),
('Integrirani otroški sedez', 'uporabnost', 'uporabnost_main'),
('Vreca za smuci', 'uporabnost', 'uporabnost_main'),
('Mrezasta pregrada tovornega prostora', 'uporabnost', 'uporabnost_main'),
('Rolo prijaznega prostora', 'uporabnost', 'uporabnost_main'),
('Navodila za uporabo v SLO jeziku', 'uporabnost', 'uporabnost_main'),
('Dvojno dno prtljaznika', 'uporabnost', 'uporabnost_main'),
('Strešne sani', 'uporabnost', 'uporabnost_main'),
('Predpriprava za mobilni telefon', 'uporabnost', 'uporabnost_main'),
('Avtatelefon', 'uporabnost', 'uporabnost_main'),
('Potovalni racunalnik', 'uporabnost', 'uporabnost_main'),
('Komunikacijski paket', 'uporabnost', 'uporabnost_main'),
('Pomoc pri speljevanju v klanec', 'uporabnost', 'uporabnost_main'),
('Sistem za aktivno pomoc pri parkiranju', 'uporabnost', 'uporabnost_main'),
('Parkimi senzorji PDC', 'uporabnost', 'uporabnost_main'),
('Pomoc pri parkiranju: kamera', 'uporabnost', 'uporabnost_main'),
('Pomoc pri parkiranju: prednji senzorji', 'uporabnost', 'uporabnost_main'),
('Pomoc pri parkiranju: zadnji senzorji', 'uporabnost', 'uporabnost_main'),
('Pomoc pri parkiranju: pogled 360 stopinj', 'uporabnost', 'uporabnost_main'),
('Vzratna kamera', 'uporabnost', 'uporabnost_main'),
('Bone stopnice', 'uporabnost', 'uporabnost_main'),
('Vlecna kijuka', 'uporabnost', 'uporabnost_main'),
('Vozilo priagojeno invalidu', 'uporabnost', 'uporabnost_main'),

-- SEDEZI IN VRATA
('Sedežev: 2', 'sedeži_in_vrata', 'sedeži'),
('Sedežev: 4', 'sedeži_in_vrata', 'sedeži'),
('Sedežev: 5', 'sedeži_in_vrata', 'sedeži'),
('Sedežev: 5+2', 'sedeži_in_vrata', 'sedeži'),
('Sedežev: 7', 'sedeži_in_vrata', 'sedeži'),
('Sedežev: 8', 'sedeži_in_vrata', 'sedeži'),
('Bus 30+', 'sedeži_in_vrata', 'sedeži'),
('Usnjeni sedeži', 'sedeži_in_vrata', 'sedeži'),
('Delno usnjeni sedeži', 'sedeži_in_vrata', 'sedeži'),
('Alcantara sedeži', 'sedeži_in_vrata', 'sedeži'),
('Sklopiva klop 60/40', 'sedeži_in_vrata', 'sedeži'),
('Sklopiva klop 40/20/40', 'sedeži_in_vrata', 'sedeži'),
('Obloga vrat - les', 'sedeži_in_vrata', 'obloge_vrat'),
('Obloga vrat - aluminij', 'sedeži_in_vrata', 'obloge_vrat'),
('Obloga vrat - karbon', 'sedeži_in_vrata', 'obloge_vrat'),
('Obloga vrat - krom', 'sedeži_in_vrata', 'obloge_vrat'),
('Vrat: 2', 'sedeži_in_vrata', 'vrata'),
('Vrat: 3', 'sedeži_in_vrata', 'vrata'),
('Vrat: 4', 'sedeži_in_vrata', 'vrata'),
('Vrat: 5', 'sedeži_in_vrata', 'vrata'),

-- PODVOZJE
('Platisca (ALU)', 'podvozje', 'platisca'),
('Zavorni sistem (ABS)', 'podvozje', 'zavorni_sistem'),
('Pomoc pri zaviranju (BAS / DBC / EBV)', 'podvozje', 'zavorni_sistem'),
('Samodejna zapora diferenciala (ASD / EDS)', 'podvozje', 'zavorni_sistem'),
('Elektronski program stabilnosti (ESP / DSC)', 'podvozje', 'stabilnost'),
('Elektronski nadzor Blaiseilnikov (EDC)', 'podvozje', 'stabilnost'),
('Regulacija nivoja podvozja (ADS)', 'podvozje', 'stabilnost'),
('Stirikolesni volan (4WS / 4CONTROL)', 'podvozje', 'stabilnost'),
('Regulacija zdrsa pogonskih koles (ASR / DTC)', 'podvozje', 'stabilnost'),
('Elektronski sistem za bolisi opnijem koles ETS', 'podvozje', 'stabilnost'),
('Športno podvozje', 'podvozje', 'podvozje_vrsta'),
('Aktivno vzmetenje (ABC - Active Body Control)', 'podvozje', 'podvozje_vrsta'),
('Zracno vzmetenje', 'podvozje', 'podvozje_vrsta'),
('Štirikolesni pogon (4x4 / 4WD / Quattro)', 'podvozje', 'podvozje_vrsta'),

-- VARNOST
('Airbag - voznik', 'varnost', 'airbag'),
('Airbag - sopotnik', 'varnost', 'airbag'),
('Airbag - stranski (vratni)', 'varnost', 'airbag'),
('Airbag - zavesni', 'varnost', 'airbag'),
('Airbag - kolenski', 'varnost', 'airbag'),
('Nadzor zracnega tlaka v pnevmatikah (RDK)', 'varnost', 'svetila'),
('Xenonski zarometi', 'varnost', 'svetila'),
('Bi-xenonski zarometi', 'varnost', 'svetila'),
('Samodejno upravljanje dolgih luzi', 'varnost', 'svetila'),
('LED zarometi', 'varnost', 'svetila'),
('Prednje (dnevne) LED luci', 'varnost', 'svetila'),
('Zadnje LED luci', 'varnost', 'svetila'),
('Meglenke', 'varnost', 'svetila'),
('Adaptive light / dinamicno prilagodijivi zarometi', 'varnost', 'svetila'),
('3. zavorna luc', 'varnost', 'svetila'),
('Naprava za pranie zarometov', 'varnost', 'svetila'),
('Head-Up display', 'varnost', 'asistence'),
('Sistem za ohranjanje voznega pasu', 'varnost', 'asistence'),
('Sistem za opozarjanje na mrtvi kot', 'varnost', 'asistence'),
('Sistem za prepoznavo prometnih znakov', 'varnost', 'asistence'),
('Senzor za dez', 'varnost', 'asistence'),
('Sistem za samodejno zaviranje v sili', 'varnost', 'asistence'),
('Opozorilnik spremembe voznega pasu', 'varnost', 'asistence'),
('Opozorilnik varnostne razdalje', 'varnost', 'asistence'),
('Alarmna naprava', 'varnost', 'zascita'),
('Blokada motorja', 'varnost', 'zascita'),
('Kodno varovan vzign motorja', 'varnost', 'zascita'),
('Rezervno kolo normalne dimenzije', 'varnost', 'pnevmatike'),
('Run-Flat pnevmatike', 'varnost', 'pnevmatike'),

-- ZUNANJOST
('Roofracks - Strešne sani', 'zunanjost', 'zunanjost_main'),
('Towbar - Vlecna kljuka', 'zunanjost', 'zunanjost_main'),
('Zasenčena stekla', 'zunanjost', 'zunanjost_main'),
('Privacy stekla', 'zunanjost', 'zunanjost_main'),
('Karbon paket zunanj', 'zunanjost', 'zunanjost_main'),
('Športni izpuh', 'zunanjost', 'zunanjost_main'),
('Automatski žarometi', 'zunanjost', 'zunanjost_main'),
('Označevalne luci LED', 'zunanjost', 'zunanjost_main'),

-- GARANCIJA IN STANJE
('Vozilo ima garancio', 'garancija_stanje', 'garancija'),
('Vozilo ima jamstvo', 'garancija_stanje', 'garancija'),
('Vozilo ima oldtimer certifikat', 'garancija_stanje', 'garancija'),
('Servisna knjiga', 'garancija_stanje', 'garancija'),
('Poln servis', 'garancija_stanje', 'garancija'),
('Garažirano', 'garancija_stanje', 'garancija'),
('Brezhibno', 'garancija_stanje', 'garancija'),
('Ne kadi', 'garancija_stanje', 'garancija'),
('Prvi lastnik', 'garancija_stanje', 'garancija'),
('Vozilo je registrirano', 'garancija_stanje', 'registracija'),
('Vozilo je tecnicno pregledano', 'garancija_stanje', 'registracija'),
('Tehnicni pregled velja do', 'garancija_stanje', 'registracija')
ON CONFLICT (name) DO NOTHING;
